lib/modules/onc_program/bulk_data_export_sequence.rb, lib/modules/onc_program/test/bulk_patient_export_sequence_test.rb
Add BDE-10 to test DELETE request
**Submitter:**
https://oncprojectracking.healthit.gov/support/browse/FI-706
Name:
Name:
=> FI-706 Add test for Bulk Data Server DELETE request

lib/modules/us_core_guidance/clinicalnotes_sequence.rb
Add additional description to BDGV-09 explaining the reason for clinical notes match test
**Submitter:**
Name:
Name:
=> FI-664-ClinicalNotes-description

lib/app/utils/exceptions.rb
Add Errno::ECONNRESET to captured exception list.
**Submitter:**
Name:
Name:
=> Add Errno::ECONNRESET to exceptions handling

lib/modules/onc_program/bulk_data_group_validation_sequence.rb
Switch Bulk Data validation to from internal FHIR model validator to external FHIR validator service
**Submitter:**
Name:
Name:
=> Fi 732 bulk data validation

lib/app/models/module/test_procedure.rb, lib/modules/onc_program_procedure.yml, lib/tasks/tasks.rake
Updates to test matrix output, test procedure mapping, and test descriptions.
**Submitter:**
Name:
Name:
=> Improve test matrix export.

generator/uscore/templates/access_verify_sequence.rb.erb, lib/app/models/module/test_group.rb, lib/app/views/onc_program.erb, lib/app/views/prerequisite_field.erb, lib/app/views/test_case.erb, lib/modules/onc_program/bulk_cache_check_sequence.rb, lib/modules/onc_program/onc_parameters.rb, lib/modules/onc_program/onc_visual_inspection_sequence.rb, lib/modules/onc_program/smart_invalid_aud_sequence.rb, lib/modules/onc_program/smart_invalid_launch_sequence.rb, lib/modules/onc_program/token_revocation_sequence.rb, lib/modules/onc_program_module.yml, lib/modules/uscore_v3.1.0/access_verify_restricted_sequence.rb, lib/modules/uscore_v3.1.0/access_verify_unrestricted_sequence.rb
We need somewhere to put the extra tests that don't quite fit into the existing scenarios.  Here is a proof of concept.  Since each one may require a little explanation / setup, I have it set so you have to run them each one-off.
**Submitter:**
Name:
Name:
=> Add one more high-level step for tests that don't fit elsewhere.

lib/app/views/missing_valuesets.erb
See https://github.com/onc-healthit/inferno-program/issues/90
=> Fix terminology help link

lib/modules/onc_program/bulk_data_group_validation_sequence.rb
The Pull Request has two minor UI fix:
1) added missing end quote mark for invalidate content-type
2) added bullet points for error message.
**Submitter:**
Name:
Name:
=> FI-762-767 Minor UI fix

lib/app/utils/tls_tester.rb, lib/modules/onc_program/onc_smart_discovery_sequence.rb
It is not a SHOULD requirement -- it is 'shall' for ONC.
**Submitter:**
Name:
Name:
=> FI-816 Update wording on TLS and a capability statement test.

README.md, lib/app/views/onc_program.erb, lib/modules/onc_program/onc_parameters.rb, lib/modules/onc_program/onc_standalone_token_refresh_sequence.rb, lib/modules/onc_program/shared_onc_launch_tests.rb, lib/modules/onc_program/token_revocation_sequence.rb, lib/modules/onc_program_module.yml
Add token revocation sequence.
**Submitter:**
Name:
Name:
=> FI-735 Token revocation implementation.

lib/modules/onc_program/bulk_data_group_validation_sequence.rb, lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb
Pull Request contains these changes:
1) Add Organization validation test
2) Add Location validation test using FHIR spec
3) Reorganize tests following the same order as single patient validation
4) Add unit test for Location's guess_profile result
**Submitter:**
Name:
Name:
=> 853 Add Organization and Location validation tests

lib/app/views/onc_program.erb, lib/modules/onc_program/onc_parameters.rb, lib/modules/onc_program/onc_smart_discovery_sequence.rb, lib/modules/onc_program/onc_standalone_public_launch_sequence.rb, lib/modules/onc_program/onc_standalone_smart_discovery_sequence.rb, lib/modules/onc_program/onc_standalone_token_refresh_sequence.rb, lib/modules/onc_program/shared_onc_launch_tests.rb, lib/modules/onc_program_module.yml, public/css/styles.css
Adds public launch requirement to the 'other' tests.
**Submitter:**
Name:
Name:
=> FI-854 Add standalone launch with public client.

lib/app/views/onc_program.erb, lib/modules/onc_program/onc_parameters.rb, lib/modules/onc_program/onc_standalone_launch_sequence.rb, lib/modules/onc_program/onc_standalone_public_launch_sequence.rb, lib/modules/onc_program/onc_standalone_restricted_launch_sequence.rb, lib/modules/onc_program/onc_visual_inspection_sequence.rb
=> fi-852 Attestation for relatedperson and practitionerrole.

lib/modules/onc_program/bulk_data_authorization_sequence.rb, lib/modules/onc_program/bulk_data_export_sequence.rb, lib/modules/onc_program/bulk_data_group_validation_sequence.rb, lib/modules/onc_program/shared_onc_launch_tests.rb
Pull requests added link for TLS 1.2 requirement.
**Submitter:**
Name:
Name:
=> Add link for TLS requirement

config.yml, generator/uscore/templates/sequence.rb.erb, lib/modules/onc_program/bulk_data_group_validation_sequence.rb, lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb, lib/modules/uscore_v3.1.0/us_core_encounter_sequence.rb, lib/modules/uscore_v3.1.0/us_core_location_sequence.rb, lib/modules/uscore_v3.1.0/us_core_organization_sequence.rb, lib/modules/uscore_v3.1.0/us_core_practitioner_sequence.rb, lib/modules/uscore_v3.1.0/us_core_practitionerrole_sequence.rb
This Pull Rquest includes changes
* Add PractitionerRole and RelatedPerson sequences
* Add test logic that bulk data export must have at least one US Core Encounter resource
* Fix some text description.
**Submitter:**
Name:
Name:
=> FI-968 Bulkdata USCDI alignment

lib/modules/onc_program_procedure.yml
Updates program matrix to match changes introduced in the [TP v1.1](https://www.healthit.gov/test-method/standardized-api-patient-and-population-services#ccg)
=> Update program procedure to match tp v1.1

lib/modules/onc_program/bulk_data_group_validation_sequence.rb
Fix a copy/paste error
**Submitter:**
Name:
Name:
=> Fix a copy/paste error

config.yml, lib/app/endpoint.rb, lib/app/endpoint/home.rb, lib/app/helpers/configuration.rb, lib/app/views/layout.erb, public/js/app.js
This branch updates the documentation in config.yml and removes some unused entries.
**Submitter:**
Name:
Name:
=> FI-1011: Update config.yml documentation

config.yml
New patients were added to the reference server, and that changed the patient IDs. This PR adds the new IDs to the reference server preset configuration.
**Submitter:**
Name:
Name:
=> FI-895: update patient IDs to the new ones for Must Support

lib/modules/onc_program/onc_visual_inspection_sequence.rb
=> Minor wording update to patient profile visual inspection.

README.md
Added link to walkthrough in Reference Implementation
=> Add walkthrough to readme

lib/app/views/onc_program.erb, lib/modules/onc_program/onc_visual_inspection_sequence.rb, lib/modules/onc_program_procedure.yml
This updates the test procedure to match the most recent publication and slightly alters wording in one of the visual inspection checks.
=> Update test procedure to match most recent publication.

lib/version.rb
=> Update version to v1.6.1-pre

lib/app/endpoint/home.rb, lib/app/utils/oauth2_error_messages.rb
Ensures all halt messages are html escaped.
=> FI-1365 Ensure all halt messages are escaped.

README.md
Adds announcement that g10 tests are moving to the README
=> g10 test move README annoucement

lib/app/views/deprecation_message.erb
Updates message on inferno-program to have specific end date for hosting on inferno.healthit.gov.
=> Update message for end of hosting.

lib/app/views/default.erb, lib/app/views/deprecation_message.erb, lib/app/views/guided.erb, lib/app/views/onc_program.erb
=> Update depreciation message and also add to every page.
