- lib/app/views/index.erb
Minor spacing issue of footer fix due to missed `</div>` on index page.
> Fix spacing issue on index.

- config.yml
- lib/modules/onc_program_module.yml
This branch fixes the obsolete program EHR launch scopes (particularly the use of `profile` instead of `fhirUser`).
The default set in the module yaml didn't work because those defaults are only used when the input is blank, which is not the case for scopes (https://github.com/onc-healthit/inferno-program/blob/master/public/js/app.js#L196).
**Submitter:**
- n/a Tests/code quality metrics have been run locally and pass
Name:
Name: @okeefm
> FI-681: Fix EHR launch scopes

- docker-compose.yml
This branch mounts the `data` directory in the inferno docker image so that the data will be persisted across docker runs.
**Submitter:**
- n/a Tests/code quality metrics have been run locally and pass
Name:
Name: @okeefm 
> FI-660: Persist data between docker runs

- config.yml
- lib/app/utils/resource_validator_factory.rb
This branch defaults to using the external validator and adds special handling so that the internal validator is used in tests
**Submitter:**
- n/a Tests/code quality metrics have been run locally and pass
Name: @arscan 
- n/a The tests appropriately test the new code, including edge cases
- n/a You have tried to break the code
Name:
> FI-693: Default to external validator

- lib/modules/us_core_guidance/clinicalnotes_sequence.rb
This branch updates the clinical notes guidance sequence to check all patient ids for each note type rather than only checking the first patient.
**Submitter:**
Name:
Name:
> FI-678: Update clinical notes sequence to check all patients

- lib/app/utils/terminology.rb
- lib/tasks/tasks.rake
This Pull Request adds the `create_non_umls_vs_validators` rake task. This task allows the Inferno user to build a subset of valueset validators that don't require the download/parsing of the UMLS Metathesaurus (a task that can take many hours, depending on computing resources). This will give Inferno users a way to get some validators up and running, so they can see what the terminology validation does, without having to go through the long process of downloading those files.
Additionally, this PR refactors much of the `create_validators` method, because it was starting to get large and repeated itself in many places. Also, the parameters in the `create_validators` method signature have been changed to named params with defaults, because we were starting to pass in quite a lot of them. …
> Fi 705 add the ability to build only non umls valuesets

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
- lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb
The changes fix the warning display on validation result, like "Count in status output (27) did not match actual number of resources returned (0)". The fix disables the count check if tester does not choose to validate all resources in bulk export. 
**Submitter:**
Name:
Name:
> FI-685 Test resource count only if validate_all resource is true

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.0/us_core_encounter_sequence.rb
This fixes an error when running the encounter sequence. Now it should pass without any errors.
**Submitter:**
Name:
Name:
> fi-721 replace instances of class with local_class in terminology validation

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
Disables TLS peer validation for the bulk streaming client. Please check both inside and outside a protected (e.g. MITRE) network when reviewing, in both true/false configs for disable_verify_peer (4 cases).
**Submitter:**
Name:
Name:
> FI-731: Disable TLS on bulk data streaming client if necessary.

- lib/app/utils/valueset.rb
- lib/tasks/tasks.rake
This PR does not have an internal ticket because it was done to allow another project to expand ValueSets individually to a CSV for another IG.
To test run:
```shell
be rake 'terminology:expand_valueset_to_file[http://hl7.org/fhir/us/core/ValueSet/birthsex, birthsex_expansion, csv]
```
You can also do this with any new ValueSet by putting that ValueSet into `tmp/terminology/fhir` (any file name that ends with `.json` should do the trick).
This also adds the ability to export the codes as a FHIR ValueSet using the expansion field.  This can be observed by setting type type to `json`
e.g.
```shell
be rake 'terminology:expand_valueset_to_file[http://hl7.org/fhir/us/core/ValueSet/birthsex, birthsex_expansion, json]
```
*Note: you'll need to have all the terminology artifacts present to run …
> Add rake task to expand single ValueSet and save it to a file

- lib/app/utils/bcp47.rb
- lib/app/utils/codesystem.rb
- lib/app/utils/terminology.rb
- lib/app/utils/valueset.rb
- test/unit/valueset_test.rb
The `Valueset` class was a uniquely-named class in that it didn't follow CamelCase convention. This PR renames it to `ValueSet`
﻿Pull requests into Inferno require the following items to be completed. Submitter and reviewer 
**Submitter:**
- N/A Internal ticket for this PR:
- N/A Internal ticket links to this PR
- N/A Internal ticket is properly labeled (Community/Program)
- N/A Internal ticket has a justification for its Community/Program label
- N/A Tests are included and test edge cases
Name: …
> Rename Valueset to ValueSet to comply with naming conventions

- lib/app/sequence_base.rb
- lib/app/views/test_inputs.erb
- lib/app/views/test_list.erb
- lib/app/views/test_log.erb
- lib/app/views/test_outputs.erb
- lib/app/views/test_result_details.erb
- public/css/styles.css
Allow markdown formatting in error messages
**Submitter:**
Name:
Name:
> FI-482: Allow formatted error messages

- lib/app/endpoint/home.rb
- lib/app/models/request_response.rb
This prevents html from being rendered in responses.
**Submitter:**
Name:
Name:
> FI-508: Unescape unicode in responses

- generator/uscore/templates/access_verify_sequence.rb.erb
- lib/modules/uscore_v3.1.0/access_verify_restricted_sequence.rb
- lib/modules/uscore_v3.1.0/access_verify_unrestricted_sequence.rb
Access verify tests fail if server returns 400 on searches because they deny searches without filters on the access verification tests.
**Submitter:**
Name:
Name:
> FI-478 Fix case when server returns 400 without status search on access verify tests.

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
The `OpenSSL::SSL::SSLContext` object in `BulkDataGroupExportValidationSequence#streamed_ndjson_get` seems like it wasn't properly set up with the right default parameters. Calling `set_params` without any options sets what OpenSSL refers to here as "sane defaults": https://docs.ruby-lang.org/en/2.4.0/OpenSSL/SSL/SSLContext.html#method-i-set_params. This seems to fix it locally (on Suspend), but I haven't tested it from infernotest or inferno.
**Submitter:**
**Reviewer …
> Add a set_params call to ndjson GET requests, so they correctly validate SSL

- lib/modules/onc_program/onc_smart_discovery_sequence.rb
This PR makes it so the bearer token isn't added to the metadata endpoint request. To test this, run the ONC Proram Standalone Patient App tests twice. Check the metadata GET request in SMART On FHIR Discovery sequence after the second run. You shouldn't see a bearer token in the headers. 
**Submitter:**
- [] Tests are included and test edge cases
Name:
Name:
> FI-747 don't add bearer token to metadata query

- lib/app/endpoint/test_set_endpoints.rb
- public/js/app.js
This makes it so that skipped tests are expanded when the test results are done. It also fixes the "show details" text to be "hide details" for the expanded test cases.
**Submitter:**
- NA Tests are included and test edge cases
Name:
Name:
> fi-658 expand skipped tests by default

- lib/app/models/request_response.rb
When there are too many resources being streamed back, Inferno fails due to a 'frozen string error' when trying to save the requests. This is because Inferno caps the number of resources logged in the interface, and adds a message in the response body indicating it is truncated. Recent code updates to fix html encoding needs to be able to mutate strings, but this string in particular is frozen.
**Submitter:** …
> Ensure frozen literals arent mutated when saving request body.

- lib/app/models/request_response.rb
- lib/app/views/onc_program.erb
- lib/modules/onc_program/bulk_data_export_sequence.rb
- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
- lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb
If one resource is invalid, instead of raising AssertionException, saving errors in an array and continue to the next resources. So the validation does not stop at the first invalid resource.
Also add logic to collect resources for response logging.
Add two more unit tests
**Submitter:**
Name:
Name:
> FI-768 Validate all resources even some is invalid

- lib/app/views/onc_program.erb
ONC program requires bulk data client register with JWK Sets URL specified in SMART Backend Services: Authorization Guide Section 5 (http://hl7.org/fhir/uv/bulkdata/authorization/index.html#registering-a-smart-backend-service-communicating-public-keys). To avoid confusion, the "Manual Key Registration" section from Multi-Patient Query test preparation dialog is removed.
**Submitter:**
Name:
Name:
> FI-736 Remove "Manual Key Registration" Section

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
`OpenSSL::SSL::Context#set_params` apparently was setting params even when SSL verification was turned off. This is not the correct behavior, so this PR adds a conditional to check that the `VERIFY_PEER` and `VERIFY_NONE` constants are not the same (an indicator that SSL verification has been turned off).
To test:
* Ensure that SSL verification is turned off in `config.yml` (set `disable_verify_peer` to `true`), and restart Inferno
* Run the Multi-patient query sequence, and ensure that all the tests complete (aka, don't throw a `self-signed certificate in cert chain` error)
* Turn SSL verification back on (set `disable_verify_peer` to `false`), and restart Inferno
* Run the same sequence, and ensure that the majority of the tests fail (aka, _do_ throw `self-signed certificate in cert …
> FI-776: fix set_params in development

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
- lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb
The changes handles both empty line in NDJSON file and empty NDJSON file.
empty NDJSON file are reported the same as server has no resources to export.
empty NDJOSN line is ignored during process.
**Submitter:**
Name:
Name:
> Handle Empty Line in NDJSON file

- lib/modules/onc_program/onc_token_refresh_sequence.rb
- lib/modules/onc_program/test/onc_token_refresh_sequence_test.rb
A requirement of ONC certification is that systems under test issue new refresh tokens when access tokens are refreshed.  This PR updates the ONC refresh token test to have an additional check to make sure that they don't match.
This requirement is technically only for apps that 'can protect a client secret', which is interpreted here as 'confidential clients', so the test is omitted if it is for a public client.
**Submitter:**
Name:
Name:
> Update ONC refresh token test to require new refresh token be issued.

- generator/uscore/templates/access_verify_sequence.rb.erb
- lib/app/views/onc_program.erb
- lib/modules/onc_program/onc_parameters.rb
- lib/modules/onc_program/onc_standalone_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_restricted_launch_sequence.rb
- lib/modules/onc_program/shared_onc_launch_tests.rb
- lib/modules/onc_program_module.yml
- lib/modules/uscore_v3.1.0/access_verify_restricted_sequence.rb
- lib/modules/uscore_v3.1.0/access_verify_unrestricted_sequence.rb
This updates the limited access test so that Inferno (as an app) requests full permissions again, but then expects the user to select a subset consistent with the resources that the tester entered in the UI.  Additionally, the tester is expected to NOT select 'offline_access', to prove that the server does not blindly accept the app's request for that level of permission.
Testing this is a challenge, because our reference server currently does not provide a modal to select a subset of resources.  Logica health can do this though.
applicable, note it's not applicable ("N/A") and check the box. For …
> Have limited access check request all scopes and expect tester to select subset in EHR interface

- lib/app/endpoint/oauth2_endpoints.rb
- lib/app/endpoint/test_set_endpoints.rb
- lib/app/helpers/browser_logic.rb
- lib/app/models/sequence_result.rb
- lib/app/models/test_result.rb
- lib/app/sequence_base.rb
- lib/app/utils/exceptions.rb
- lib/modules/onc_program/smart_invalid_aud_sequence.rb
- lib/modules/onc_program/smart_invalid_launch_sequence.rb
- lib/modules/onc_program_module.yml
Add two new negative launch tests.  One test is for standalone launches and tests that the server fails if an invalid AUD parameter is passed.  The other is for EHR launches and tests that if Inferno changes the launch parameter received during the launch then the authorization fails.
I suspect this will need a lot more documentation / explanation in the app to describe how it works.
**Submitter:**
Name:
where appropriate, and accomplishes the task's …
> FI-196 Add invalid launches.

- config.yml
- lib/app/utils/validation.rb
- lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb
Changes in this PR:
1) return nil when Observation resource does not match any predefined US core profile
**Submitter:**
Name:
Name:
> FI-814 observation profile

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
- lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb
Changes in this pull request:
1) Skip BDGV-04 validate-two-patients test when the patients output is empty
**Submitter:**
Name:
Name:
> FI-817 multi patient test

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.0/us_core_implantable_device_sequence.rb
This adds a check to validate the non-implantable devices against base fhir.
**Submitter:**
Name:
Name:
> Fi 839 validate non implantable devices

- lib/app/models/server_capabilities.rb
- lib/modules/us_core_guidance/us_core_r4_capability_statement_sequence.rb
- test/unit/server_capabilities_test.rb
This fixes a problem where warnings were being given for unsupported profiles because canonical urls weren't being recognized.
**Submitter:**
Name:
Name:
> FI-750: Support canonical urls in capabilities test

- lib/app/sequence_base.rb
This fixes an issue where we give an error when trying to perform a search with system for a codeableconcept that cannot be found. 
**Submitter:**
Name:
Name:
> fi-840 Fix error when cannot find codeableconcept search value

- bin/run_terminology.sh
- terminology_compose.yml
This branch updates the terminology processing script to ensure that 10 GB of ram are available before processing.
With < 10 GB:
```
ᐅ docker-compose -f terminology_compose.yml up
Recreating inferno-program_terminology_builder_1 ... done
Attaching to inferno-program_terminology_builder_1
terminology_builder_1  | 10 GB of RAM must be available in order to process the terminology, but only 8 GB is available
inferno-program_terminology_builder_1 exited with code 1
```
With 10 GB:
```
ᐅ docker-compose -f terminology_compose.yml up
Starting inferno-program_terminology_builder_1 ... done
Attaching to inferno-program_terminology_builder_1
terminology_builder_1  | UMLS Username environment variable is empty
inferno-program_terminology_builder_1 exited with code 1
```
**Submitter:**
- n/a Tests …
> FI-830: Check available RAM for terminology processing

- lib/modules/onc_program/onc_smart_discovery_sequence.rb
This branch adds bullets to make the error message for OSD-05 more readable (in the examples below the urls are consistent, I just changed the assertion to make the error appear).
Before:
After:
**Submitter:**
Name:
Name:
> FI-561: Fix OSD-05 error message formatting

- lib/app/endpoint/oauth2_endpoints.rb
- lib/app/utils/oauth2_error_messages.rb
- lib/app/views/default.erb
- lib/app/views/guided.erb
- lib/app/views/onc_program.erb
- test/integration/oauth2_endpoints_test.rb
- test/test_helper.rb
If during the launch process you visit Infenro's launch URI without a state, inferno will match you to the wrong instance. It should see that no state param was passed, then check if there is a cookie with the instance stored there, and redirect you to the instance in the cookie.
Previous to this fix, the logic is set up so that Inferno will find you the first instance with a state of 'nil', which will be present in any instance that hasn't yet run any inferno launches.
To recreate, simply go to https://inferno.healthit.gov/inferno/oauth2/static/redirect.
**Submitter:**
Name:
Name:
> FI-870 Ensure correct test instance found in smart redirect when no state.

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
- lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb
This change synchronize the behavior of must_support tests between single-patient and multi-patients test. 
1) Using SkipException when there are missing must_support element(s)
**Submitter:**
Name:
Name:
> Change must_support missing element to SkipException

- lib/app/models/request_response.rb
- lib/app/models/test_result.rb
RequestResponses were being shown out of order due to insufficient precision in how timestamps are stored in the database. This branch adds a new field to store their order, as shown in the screenshots below (check the order from bottom to top).
Before:
After:
**Submitter:**
Name:
Name:
> Fix ordering of RequestResponses

- .dockerignore
- .gitignore
- README.md
The terminology dockerfile instructions were too Linux-specific before (specifying that users should `EXPORT` a couple of environment variables). This PR updates the instructions to specify that those variables should be placed in a file named `.env` at the root of the inferno project. Docker-compose will pick those variables up and inject them into the terminology docker container.
The `.env` file has been added to `.gitignore`, to make sure it doesn't get accidentally committed, and `.dockerignore`, to keep it from getting mapped into any docker containers.
applicable, note it's not applicable …
> Update the terminology Docker instructions in the readme to include the use of a .env file, and add that file to the .ignores

- config.yml
- lib/app/views/layout.erb
This cleans up the presets for when you load up inferno on localhost.  It also fixes two links to the wrong github repo on the bottom of the interface.
**Submitter:**
Name:
Name:
> Fi 884 scrub presets

- lib/app/endpoint/landing.rb
- lib/app/views/layout.erb
- public/js/app.js
Previously, we were loading the "server state" modal in on every page load, whether or not it was viewed. This was a lot of HTML to send and render every time. This PR makes it so that the server state info is rendered in its own GET request, and fetched via AJAX the first time the modal is opened.
**Submitter:**
Name:
Name:
> FI-883: Load Server State modal via AJAX

- generator/uscore/templates/access_verify_sequence.rb.erb
- lib/modules/uscore_v3.1.0/access_verify_restricted_sequence.rb
- lib/modules/uscore_v3.1.0/access_verify_unrestricted_sequence.rb
The 'Limited Scope' set of tests expects the tester (acting as a patient using an app) to deny access to a subset of the resources allowed.  For those resources that are denied, the previous version of these tests required a `401 Unauthorized` status be returned by the server.  Upon further review, `403 Forbidden` is also suitable, and may be more appropriate than 401.
This PR allows the system under test to return either.  Since this update reflects a relaxation of requirements, it is suitable for a patch update to the Inferno Program set of tests.  Additional analysis is required to determine if `403 Forbidden` is the only suitable response in this case.
This PR considered adding a warning when `401` responses did not include the `WWW-Authenticate` header, as that is a requirement in …
> FI-896 Allow 401 or 403 response on insufficient / limited access tests.

- lib/modules/onc_program/onc_token_refresh_sequence.rb
- lib/modules/onc_program/shared_onc_launch_tests.rb
- lib/modules/onc_program/test/onc_ehr_launch_sequence_test.rb
- lib/modules/onc_program/test/onc_standalone_launch_sequence_test.rb
- lib/modules/onc_program/test/onc_standalone_token_refresh_sequence_test.rb
- lib/modules/onc_program/test/onc_token_refresh_sequence_test.rb
- lib/modules/smart/shared_launch_tests.rb
- lib/modules/smart/test/shared_launch_tests_test.rb
- lib/modules/smart/test/token_refresh_sequence_test.rb
- lib/modules/smart/token_refresh_sequence.rb
Fix checks for unrequested scopes to only apply to token refresh.  This check was erroneously applied to the initial OAuth 2.0 token exchange.
[JIRA Issue](https://oncprojectracking.healthit.gov/support/browse/FI-891)
Relevant GH Issue: https://github.com/onc-healthit/inferno/issues/464
**Submitter:**
Name:
Name:
> FI-891: Token Exchange Unrequested Scopes

- lib/app/sequence_base.rb
- test/unit/sequence_base_test.rb
This PR fixes an issue when getting a value to search by when the period has no start date. It also adds more unit tests for getting a search value from a period .
**Submitter:**
Name:
Name:
> FI-888 fix end range problem and add unit tests

- generator/uscore/uscore_generator.rb
- lib/app/models/request_response.rb
- lib/app/sequence_base.rb
- lib/modules/uscore_v3.1.0/bodyheight_sequence.rb
- lib/modules/uscore_v3.1.0/bodytemp_sequence.rb
- lib/modules/uscore_v3.1.0/bodyweight_sequence.rb
- lib/modules/uscore_v3.1.0/bp_sequence.rb
- lib/modules/uscore_v3.1.0/headcircum_sequence.rb
- lib/modules/uscore_v3.1.0/heartrate_sequence.rb
- lib/modules/uscore_v3.1.0/pediatric_bmi_for_age_sequence.rb
- lib/modules/uscore_v3.1.0/pediatric_weight_for_height_sequence.rb
- lib/modules/uscore_v3.1.0/resprate_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_diagnosticreport_lab_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_diagnosticreport_note_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_documentreference_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_goal_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_immunization_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_observation_lab_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_procedure_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_pulse_oximetry_sequence.rb
- test/unit/sequence_base_test.rb
This PR fixes a bug where lt and le comparator searches will search by the start date instead of the day after the start date of periods. This is caused by a recent change to how the normal period searches are performed. 
To test, the procedure sequence should pass with the reference data set.
**Submitter:**
Name:
Name:
> fix period comparator search

- lib/modules/onc_program/onc_smart_discovery_sequence.rb
- lib/modules/onc_program/onc_standalone_smart_discovery_sequence.rb
The SMART discovery sequence current provides warnings when optional fields are not provided in the two metadata endpoints.  These optional fields are unlikely to be implemented by anyone undergoing certification, and it is even less likely they will point to standardized capabilities because there is little to no guidance on how to implement them.  Therefore, do not flag their absence as a warning in the Program Edition.
Note: as an example, our reference implementation does not currently implement them, because it is unclear exactly what is the right way to do so.
**Submitter:**
Name:
Name:
> Remove warnings for optional metadata in SMART discovery sequence.

- lib/app/sequence_base.rb
Addresses a bug in validating codes for extensible bindings where warnings were erroneously given for codes _not_ in the ValueSet, but _in_ the CodeSystem.  This only impacted CodeableConcepts and the original code was throwing a warning if `any` of the codes were valid codes, when really it should have been if any were not.
Fixes: FI-910, FI-911, FI-912, FI-913, FI-914, FI-915, FI-916, FI-917, FI-918
**Submitter:**
Name:
Name:
> FI-910: Fix Invalid Warnings

- README.md
- lib/tasks/tasks.rake
Adds a rake task for checking for the inclusion of a code in a CodeSystem or ValueSet:
Example of checking against a ValueSet :
```shell
be rake "terminology:check_code[91935009,http://snomed.info/sct, http://hl7.org/fhir/us/core/ValueSet/us-core-allergy-substance]"
X http://snomed.info/sct|91935009  is not in http://hl7.org/fhir/us/core/ValueSet/us-core-allergy-substance
```
Example of checking against a CodeSystem (just omit the ValueSet argument):
```shell
be rake "terminology:check_code[91935009,http://snomed.info/sct]"
✓ http://snomed.info/sct|91935009  is in http://snomed.info/sct
```
**Submitter:**
Name:
Name:
> FI-919: Check code inclusion rake task

- lib/app/utils/validation.rb
Create method resource_contains_categroy in validation.rb to check if a resource has required category.code and categroy.system
**Submitter:**
Name:
Name:
> Add resource_contains_category method

- generator/uscore/static_test/access_verify_restricted_test.rb
- generator/uscore/static_test/access_verify_unrestricted_test.rb
- generator/uscore/templates/access_verify_sequence.rb.erb
- lib/modules/onc_program/onc_standalone_restricted_launch_sequence.rb
- lib/modules/uscore_v3.1.0/access_verify_restricted_sequence.rb
- lib/modules/uscore_v3.1.0/access_verify_unrestricted_sequence.rb
- lib/modules/uscore_v3.1.0/test/access_verify_restricted_test.rb
- lib/modules/uscore_v3.1.0/test/access_verify_unrestricted_test.rb
This update refines our 'Access verify' set of tests.  The intent of these tests are to ensure that patients have control over what scopes are granted to the application.  We accomplish this by having one sequence that requires full scopes, and verifies that the scopes returned by the server have all the required scopes to get all USCDI references.  And another sequence that prompts the tester to choose a subset of scopes (defaulting to Observation, Condition and Patient), and then the tester is supposed to only grant those scopes, and Inferno verifies that is the case for what is returned.
Previously, these tests passed more than they should have (you could allow for extra scopes in certain cases).  This PR much more thoroughly ensures that the logic is correct, and contains a number of …
> FI-920 Fix verify check.

- lib/app/ext/fhir_models.rb
- lib/app/sequence_base.rb
- lib/app/utils/hl7_validator.rb
- test/fixtures/bundle_primitive_extensions.json
- test/fixtures/contained_resource.json
- test/fixtures/procedure_primitive_extension.json
- test/unit/fhir_models_test.rb
- test/unit/hl7_validator_test.rb
Closes #143. 
This PR solves an issue where parsing resources into `fhir_models` would "drop" data that `fhir_models` doesn't support (the specific instance was with primitive extensions). 
The way this is solved is by adding in a pair of attributes on the `FHIR::Model` base class, called `source_text` and `source_hash`.
When parsing a FHIR Object out of JSON or XML, (using `from_contents`, `from_json`, or `from_xml`), the text used for that parsing will be serialized onto `source_text`.
When creating a FHIR Object out of a hash (as when creating nested FHIR Resources), the hash used to create the object will be serialized onto `source_hash`.
We also added a `source_contents` method to the `FHIR::Model` class. This method will return either: `@source_text`, if it isn't `nil`, or a …
> FI-934 Add monkey patches to fhir_models to save source_content 

- lib/app/views/onc_program.erb
- lib/modules/onc_program/onc_parameters.rb
- lib/modules/onc_program/onc_visual_inspection_sequence.rb
- lib/modules/onc_program_procedure.yml
Addresses #151 
Adds two new visual inspection / demonstrations for the following gaps:
* Patient Demographics - Suffix
* Patient Demographics - Previous Name
* AllergyIntolerance.reaction
These will likely be removed when US Core releases an upcoming errata release.  To view these, in the Program Edition, go to 'Other' tests and run the 'Visual Inspection and Attestation' test (the very last one).
**Submitter:**
Name:
Name:
> FI-941 Add us core gaps demonstrations.

- lib/app/views/onc_program.erb
- lib/modules/onc_program/onc_visual_inspection_sequence.rb
Small fix to remove language requiring specific FHIR elements to be checked.  In the test description we reference the preferred elements.
**Submitter:**
Name:
Name:
> FI-944 Remove requirement to use a specific FHIR element in visual inspection

- lib/app/views/onc_program.erb
The bulk data scope input box defaults to having 'system/system.read' which is invalid, and doesn't include 'system/RelatedPerson.read' which is allowed.
These should align with the resource scopes that auto-fill in the SMART App Launch related tests.
**Submitter:**
Name:
Name:
> FI-974 Fix scopes that prefill for bulk data

- lib/app/views/report.erb
The "Resource References" in the report may no longer be accurate because this data is cleared on each new launch.  Since we now have another launch in the 'other' section, under the regular workflow of the tool you will clear out the references just prior to completion of the tests.  For now, remove the references so that this misleading information is no longer provided.  A larger task of revisiting what is useful in the report may be done in the future.
**Before:**
**After:**
**Submitter:**
Name:
Name:
> FI-945 Remove resource references from report.

- lib/app/utils/hl7_validator.rb
- lib/app/views/server_state.erb
- test/unit/hl7_validator_test.rb
This PR adds a new section to the "Server Configuration" modal to display the validator version info, which is useful for certification purposes.
**Submitter:**
Name:
Name:
> FI-925: Display validator version info

- config.yml
Added preset values so that if the inferno reference server preset option is used, fields in the  Multi-Patient Api are automatically populated
**Submitter:**
Name:
Name:
> added preset values for bulk data fields

- config.yml
Minor fix on preset to point to the http(s) version of inferno.healthit.gov for the bulk data server.
> Fix http(s) on bulk data server preset.

- lib/app/sequence_base.rb
- lib/modules/argonaut/test/argonaut_careteam_sequence_test.rb
- lib/modules/argonaut/test/argonaut_diagnostic_report_sequence_test.rb
- test/unit/sequence_base_test.rb
This branch checks that the correct resource type is returned when resolving a reference.
**Submitter:**
Name:
Name:
> FI-996: Check resolved reference types

- generator/uscore/uscore_generator.rb
- lib/app/sequence_base.rb
- lib/modules/uscore_v3.1.0/bodyheight_sequence.rb
- lib/modules/uscore_v3.1.0/bodytemp_sequence.rb
- lib/modules/uscore_v3.1.0/bodyweight_sequence.rb
- lib/modules/uscore_v3.1.0/bp_sequence.rb
- lib/modules/uscore_v3.1.0/headcircum_sequence.rb
- lib/modules/uscore_v3.1.0/heartrate_sequence.rb
- lib/modules/uscore_v3.1.0/pediatric_bmi_for_age_sequence.rb
- lib/modules/uscore_v3.1.0/pediatric_weight_for_height_sequence.rb
- lib/modules/uscore_v3.1.0/resprate_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_allergyintolerance_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_careplan_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_careteam_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_condition_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_diagnosticreport_lab_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_diagnosticreport_note_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_documentreference_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_goal_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_immunization_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_implantable_device_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_medicationrequest_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_observation_lab_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_patient_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_procedure_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_pulse_oximetry_sequence.rb
- lib/modules/uscore_v3.1.0/us_core_smokingstatus_sequence.rb
This PR changes how we save delayed references. Before we were using walk_resource which keeps indexing ([x]) in the path which caused issues. resolve_path just finds all values for the given path so we don't have to worry about that. I also fixed an issue when save delayed resources in provenance resources. 
**Submitter:**
Name:
Name:
> Fi 1024 fix save delayed references

- docker-compose.yml
This PR pins inferno-program's validator to a specific version of fhir-validator-service, so we can begin the deprecation process for fhir-validator-wrapper. This version is the same as what is currently in fhir-validator-wrapper, so this should result in no change in functionality.
**Submitter:**
Name:
Name:
> FI-984: Move fhir-validation to use the fhir-validator-service v0.1.0 tag

- generator/uscore/metadata_extractor.rb
- lib/modules/uscore_v3.1.0/profile_definitions/us_core_pulse_oximetry_definitions.rb
- lib/modules/uscore_v3.1.0/us_core_pulse_oximetry_sequence.rb
This just removes the other Component.value[x] must supports besides valueQuantity. To note, there needs to be work done on must support sub-elements of slices. But this requires a pretty major change and will require restructuring of how we're currently handling must supports.
**Submitter:**
Name:
Name:
> FI - 1041 don't check for other component.value[x] must supports in pulse oximetry

- README.md
A recent Github issue brought to our attention that variables used in `.env` behave differently than expected with respect to quotation marks. According to https://docs.docker.com/compose/env-file/ (last bullet under `Syntax Rules`), quotation marks surrounding a variable in `.env` will be considered part of the variable, which will mess up terminology building. This PR adds a note to the README letting people know, and also does some Markdown Lint/other cleanups in the Terminology section.
Requests do not …
> Add a note to the readme about .env variables and quotes

- docker-compose.yml
- lib/app/utils/validation.rb
- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
- lib/modules/us_core_guidance/us_core_r4_capability_statement_sequence.rb
Builds on update to v3.1.1 to ensure that the profile identification tool chooses the right profile head circumference profile to validate against based on the code.
FYI @yunwwang
> Update profile guesser to point to new head circumference profile.

- lib/app/views/onc_program.erb
- lib/modules/onc_program/onc_parameters.rb
- lib/modules/onc_program/onc_visual_inspection_sequence.rb
- lib/modules/onc_program_procedure.yml
This does the following:
* Adds attestation for native clients
* Removes attestations for relatedperson / practitionerrole because they are no longer referenced by USCDI-mapped profiles
* Removes AllergyIntolerance reaction attestation becasue that is now handled by US Core v3.1.1 must supports
* Updates test procedure language to match newest published version
* Updates mapping to ensure test numbers are mapped to their appropriate test.
> Update attestations for new ccg.

- generator/uscore/templates/access_verify_sequence.rb.erb
- generator/uscore/templates/unit_tests/access_verify_restricted_unit_test.rb.erb
- generator/uscore/templates/unit_tests/access_verify_unrestricted_unit_test.rb.erb
- lib/app/views/onc_program.erb
- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
- lib/modules/uscore_v3.1.1/access_verify_restricted_sequence.rb
- lib/modules/uscore_v3.1.1/access_verify_unrestricted_sequence.rb
- lib/modules/uscore_v3.1.1/test/access_verify_restricted_test.rb
- lib/modules/uscore_v3.1.1/test/access_verify_unrestricted_test.rb
This removes PractitionerRole and RelatedPerson from the SMART Scopes, and related language.
**Submitter:**
Name:
Name:
> FI-1078 Scrub scopes of PractitionerRole and RelatedPerson

- generator/uscore/metadata_extractor.rb
- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/head_occipital_frontal_circumference_percentile_sequence.rb
- lib/modules/uscore_v3.1.1/profile_definitions/us_core_implantable_device_definitions.rb
- lib/modules/uscore_v3.1.1/us_core_implantable_device_sequence.rb
This PR makes it so that either carrierAIDC or carrierHRF is found in the must support test. I take out both elements from the must support metadata and add a special check for udicarrier.carrierAIDC and udicarrier.carrierHRF. 
This PR also includes a change to head_occipital_frontal_circumference_percentile_sequence which was made by the generator. I'm guessing it was just not included in another PR.
**Submitter:**
Name:
Name:
> Fi 1066-either carrieraidc carrierhrf must support

- lib/app/utils/hl7_validator.rb
There is an invariant in FHIR and US Core vital signs that has been acknowledged to be invalid.  Hopefully this will be addressed in future versions of US Core, but in the meantime we will 'mute' the error from the validator.
```
vs-1: if Observation.effective[x] is dateTime and has a value then that value shall be precise to the day [($this as dateTime).toString().length() >= 8]
uscore-1: if Observation.effective[x] is dateTime and has a value then that value shall be precise to the day [($this as dateTime).toString().length() >= 8]
```
Note: I recognize that we could probably just key off of the invariant key (uscore-1, vs-1), but I am skeptical that these are globally unique forever, so instead of just keying off them, I do it plus the first N characters of the description (because …
> FI-1083 Fix invalid invariants in FHIR v4.0.1 and US Core v3.1.1

- lib/modules/onc_program/onc_token_refresh_sequence.rb
- lib/modules/onc_program/test/onc_token_refresh_sequence_test.rb
- lib/modules/onc_program_procedure.yml
Remove 'refreshing the refresh token' tests because ONC guidance states that is not a requirement.  This includes the check that the refresh token is present after the refresh token exchange, and the check that the refresh token is different than the previous one.  There does not appear to be a requirement that the refresh token needs to be present at all after the exchange, even if its duration is being extended.
**Submitter:**
Name:
Name:
> FI-1084: Remove refreshing the refresh token test.

- lib/app/utils/hl7_validator.rb
The `us-core-1` invariant in the US Core Laboratory Result Observation profile was still being let through the issue details filter, apparently due to some incorrect text in the filter. This PR updates the text.
**Submitter:**
Name:
Name:
> Update text of us-core-1 invariant in ISSUE_DETAILS_FILTER

- generator/uscore/metadata_extractor.rb
- lib/modules/uscore_v3.1.1/head_occipital_frontal_circumference_percentile_sequence.rb
Slight update to generator to not include dashes in the test prefix to be consistent.
**Submitter:**
Name:
Name:
> FI-1086: Modify test prefix code to not include dashes.

- lib/app/models/request_response.rb
Currently, pressing the details button in the HTTP requests tab will fail to bring up the request details. This is because the request_index attribute is a Serial which defaults to being a key. Then the .get to retrieve the request_response expects both an id and a request_index. 
I address this by making request_index not a key. Changing the type to UUID instead of Serial also worked, but I don't know if that's the right to do it.  
btw, you also have to delete the database data in data/development_data.db before trying this.
**Submitter:**
- [] Tests are included and test edge cases
Name:
Name:
> FI-1082 make request_index not a key

- lib/app/sequence_base.rb
- test/unit/sequence_base_test.rb
Fix for issue where contained references result in a hard error in the reference resolution tests.  See #221 for test data that exposes this issue (USCMR-14 has a purple error).  Before this fix, you would always fail if you were using contained resources.
**Submitter:**
Name:
Name:
> FI-1110 Fix reference resolution for contained references

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
Fixes issue in bulk data validation tests where empty chunk streamed back causes tests to error.
Could not add tests because our mocking library doesn't allow you to stream back chunks -- it just lets you send back the whole body.  So we cannot effectively self test this issue without a fair amount of work.
See internal JIRA ticket for example server configuration to replicate this issue.
**Submitter:**
Name:
Name:
> fi-1127: Fix issue where bulk data errors if empty chunk streamed back.

- .travis.yml
- README.md
- batch/inferno.healthit.gov.json
- batch/script_example.json
- docker-compose.yml
- docker/nginx.conf
If you are using `docker-compose run` to execute inferno from the command line (to run a script, for example), the `depends_on` is very important but wasn't included.
I also renamed the container names from `ruby_server` to `inferno` and `nginx_server` to `nginx` because they are better descriptions of the containers.  Docker may nag you to clean up orphaned containers due to this name change.
> Update docker compose

- config.yml
- lib/app/sequence_base.rb
- lib/modules/uscore_v3.1.1/test/fixtures/us_core_careteam.json
Add logic skipping contained reference from treating as delayed references
reference to contained resource are skipped
save_delayed_sequence_references() in sequence_base.rb
Add a MustSpported reference to a contained resource. Example provided at lib/module/uscore_v3.1.1/test/fixutres/us_core_careteam.json
> FI-1150 skip contained reference from save_delayed_reference

- lib/app/sequence_base.rb
- lib/modules/uscore_v3.1.1/test/fixtures/us_core_patient.json
- lib/modules/uscore_v3.1.1/test/us_core_patient_test.rb
when creating search_parameter, comma(,) character is replaced with "\\," to avoid conflict with FHIR multiple OR search. For example: "Dole,John" is reformed search parameter: name=Dole\\,John in order to distinguish from name=Dole,John which is searching name starts with "Dole" or "John"
While compare the result with search parameter, the "\\," in search parameter need to changed back to "," only.
Unescape "\\," in search value to ","
validate_reply_entries in sequence_base.rb
new unit test
updated testing artifact with name text
> unescape the \\, in search value

- lib/modules/onc_program/onc_smart_discovery_sequence.rb
- lib/modules/onc_program/onc_standalone_smart_discovery_sequence.rb
- lib/modules/onc_program/test/onc_smart_discovery_sequence_test.rb
- lib/modules/onc_program/test/onc_standalone_smart_discovery_sequence_test.rb
If a system implements patient-centric and practitioner-centric APIs using different FHIR endpoints, then they should not need to state support for all smart capabilities at every endpoint.
This now only ensures that the capabilities relevant to the current target use case (patient standalone vs practitioner ehr) is tested.
The only tricky part here is how to override what used to be a CONSTANT.  Please verify that this approach makes sense.
Review updated tests.  They should cover all necessary cases.
> FI-1157 Allow more flexibility in which endpoints expose which smart capabiliites

- lib/app/endpoint.rb
- test/integration/home_page_test.rb
Some Inferno tests require the application to be embedded within an EHR interface in order to demonstrate certain functionality.  Web browsers inspect the "X-Frame-Options" header to ensure that the website being included allows this behavior. By default, Sinatra includes this header for security reasons.  We need to disable it for users that want to run Inferno outside of Docker.  For Docker users, we already strip these headers out when routing the request through NGINX.
See https://github.com/onc-healthit/inferno-program/issues/235#issuecomment-786914929
This configures Sinatra to not include that header for any response.  We may consider being more discerning in the new version to only disable it for response that may be embedded in an EHR, but that would be difficult in this legacy …
> FI-1166: Remove frame embedding protection at app level.

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/bodyheight_sequence.rb
- lib/modules/uscore_v3.1.1/bodytemp_sequence.rb
- lib/modules/uscore_v3.1.1/bodyweight_sequence.rb
- lib/modules/uscore_v3.1.1/bp_sequence.rb
- lib/modules/uscore_v3.1.1/head_occipital_frontal_circumference_percentile_sequence.rb
- lib/modules/uscore_v3.1.1/heartrate_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_bmi_for_age_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_weight_for_height_sequence.rb
- lib/modules/uscore_v3.1.1/resprate_sequence.rb
- lib/modules/uscore_v3.1.1/test/us_core_patient_test.rb
- lib/modules/uscore_v3.1.1/us_core_allergyintolerance_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_careplan_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_condition_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_note_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_documentreference_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_implantable_device_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_observation_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_patient_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_procedure_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_pulse_oximetry_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_smokingstatus_sequence.rb
Our searches are set up to choose which values to populate search criteria with based on data that has already been seen.  Since it is technically valid to not populate many values in the resource, including values which may be searched by, we have to ensure that we do not pick values that are null / filled with DARs.
We are doing this properly for most searches.  However, it turns out we are not doing this properly when we re-do a "code" search with the equivalent "system|code" search.  So for the first search (just by code), we locate and use a valid code, but then when we redo the search with system, our code picks up a different resource with a code not filled in, if we are unlucky.
This only occurs if the first resource returned has no code to search by, so you have to be a little …
> FI-1176: Ensure code exists when doing code search with system.

- config.yml
After rebasing the bulk-data-server to match the smart-on-fhir version, the expected group id changed to require the db id rather than the group id key. Updated preset to have the db id.
The preset value has changed.
The config file has changed.
Test using the presets on the multi-patient tests
> updated group_id value to match rebase bulk-data-server

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/bodyheight_sequence.rb
- lib/modules/uscore_v3.1.1/bodytemp_sequence.rb
- lib/modules/uscore_v3.1.1/bodyweight_sequence.rb
- lib/modules/uscore_v3.1.1/bp_sequence.rb
- lib/modules/uscore_v3.1.1/head_occipital_frontal_circumference_percentile_sequence.rb
- lib/modules/uscore_v3.1.1/heartrate_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_bmi_for_age_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_weight_for_height_sequence.rb
- lib/modules/uscore_v3.1.1/resprate_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_allergyintolerance_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_careplan_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_careteam_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_condition_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_note_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_documentreference_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_goal_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_immunization_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_implantable_device_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_medicationrequest_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_observation_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_procedure_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_pulse_oximetry_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_smokingstatus_sequence.rb
The first search in each US Core profile sequence check both the `patient=Patient/id` and `patient=id` search variants to make sure there are the same number of results for each variant.  In the case of devices, we have special logic to filter out results that are non-implantable if a user specifies to exclude all but certain device types.  The tests do not apply the filter to both of the search variants, so if you include a code that actually filters the device results, the test will fail.
Because the logic to check for devices requires a couple of lines of code, and because there isn't much value thoroughly checking this search option for each profile, this fix simply excludes checking that both variants return the same number of results for the Implantable Device profile.  Instead, …
> Exclude devices from resource count check.

- lib/version.rb
This updates the version so that there isn't confusion about the fact that `main` is different than the 1.5.0 release.
> Update version to 1.6.0-pre

- lib/modules/onc_program/bulk_data_group_validation_sequence.rb
- lib/modules/onc_program/test/bulk_group_validation_sequence_test.rb
Allow additional values in response's content-type header
After receiving response for file download request, Inferno checks if response's content-type header contains application/fhir+ndjson
bulk_data_group_validation_sequence: change string compare to string include
add unit test for content-type header with multiple values
> Allows additional value in response's content-type

- db/config.postgres.yml
- lib/app/endpoint.rb
- lib/app/endpoint/oauth2_endpoints.rb
- lib/app/endpoint/test_set_endpoints.rb
Make ActiveRecord release connections at the end of requests.
In `endpoint.rb` If you change the `logger.debug` in the `after` block to `logger.info`, you'll see the connection info in the logs and can verify that it doesn't keep increasing.
> FI-1237: Release DB connections after requests

- generator/uscore/templates/access_verify_sequence.rb.erb
- generator/uscore/templates/unit_tests/access_verify_restricted_unit_test.rb.erb
- generator/uscore/templates/unit_tests/access_verify_unrestricted_unit_test.rb.erb
- lib/modules/onc_program/onc_standalone_restricted_launch_sequence.rb
- lib/modules/onc_program/onc_visual_inspection_sequence.rb
- lib/modules/onc_program/shared_onc_launch_tests.rb
- lib/modules/onc_program_module.yml
- lib/modules/uscore_v3.1.1/access_verify_restricted_sequence.rb
- lib/modules/uscore_v3.1.1/access_verify_unrestricted_sequence.rb
- lib/modules/uscore_v3.1.1/test/access_verify_restricted_test.rb
- lib/modules/uscore_v3.1.1/test/access_verify_unrestricted_test.rb
Addresses CCG updates regarding  the absence of a requirement for denying `offline_access` scope, and allowing systems to use `user` scopes for non-Patient compartment resources for patient app launches.  Note that this addresses both FI-1189 and FI-1188 in our internal tracker due to the close relationship of the two CCG clarifications.
For the 'limited access tests', there should be no mention of needing to deny "offline_access", and when you run the test it should pass if you allow "offline_access".
For the 'standalone patient app' tests, you can change the defaulted "patient" scope to "user" for non-patient compartment resources (and technically not encounter either since it is not uscdi v1).  Try changing some scopes to 'user', it should fail if you do it on a patient compartment …
> FI-1189 CCG Scope Updates

- README.md
- bin/run_terminology.sh
- terminology_compose.yml
- terminology_dockerfile
Need to make some changes to `terminology_dockerfile` and `terminology_compose.yml` to make them work with Inferno now that Datamapper has been removed. Also need to bump Ruby to 2.7.2. 
Remove everything from `tmp/terminology/` except `umls.zip`, and run `docker-compose -f terminology_compose.yml up --build`. Ensure it runs, and doesn't error out with `could not load database configuration. No such file - ["db/config.yml"]`
> Update the terminology dockerfile and compose file to the new datamapper-less configuration

- lib/tasks/tasks.rake
Updating running tests from tasks.rake so it reads the config file
Now tasks.rake manually reads the config file to learn about verify_peer
Change the config's disable_verify_peer Run inferno tests from rake to test and confirm that USCCAP-01 is ommited
> read config file from rake tests to set disable verify peer correctly

- lib/app/utils/bcp_13.rb
- lib/app/utils/terminology.rb
- lib/app/utils/test/bcp_13_test.rb
BCP:13 codes (aka `MIME Types`) can have optional "parameters" tacked on after the actual MIME type; like `application/fhir+json; charset=UTF-8`. This is considered "legal" in FHIR, but our Bloom Filters can't handle them, so we have to strip off anything that's not the MIME type itself before validation.
While we're at it, this PR also `downcase`s the MIME type before validation, to avoid case mismatches (since MIIME types are case-insensitive). 
The PR also adds this preprocess step to the BCP:13 bloom filter generation code, so moving forward all the MIME types coming out of the MIME::types gem will be `downcase`d.
* Ensure the bloom filters are built/present on your system
* Test a MIME type with parameters against the appropriate valueset, with a Rake task like `rake …
> Add support for "preprocessing" BCP:13 codes prior to validation

- generator/uscore/templates/access_verify_sequence.rb.erb
- lib/modules/uscore_v3.1.1/access_verify_restricted_sequence.rb
- lib/modules/uscore_v3.1.1/access_verify_unrestricted_sequence.rb
The access verification sequences were passing a string instead of a fhir model to `FHIR::Client#search`, which was causing errors to be logged.
Fixed the template for these sequences to use a `FHIR::Model` class rather than a string in their search calls. Also, #283 added some code directly to a generated sequence, so I moved it into the template.
When running the verify unrestricted access sequence, you shouldn't see these error messages in the logs:
```
ERROR | Inferno | Failed to parse application/fhir+json as resource Procedure: undefined method `ancestors' for "Procedure":String
```
> FI-1192: Fix search calls

- lib/tasks/tasks.rake
For the execute rake task, now if the inferno tests have a skip it has a return value 1 so ci workflows using this fail on skips.
rake task has return_value 1 if there are skips
1. Build this image as `onchealthit/inferno-program:release-latest`
2. Checkout the inferno-reference server on branch `add-github-ci-to-run-inferno-tests` 
3. Run `docker-compose -f ./.github/inferno/docker-compose.yml run -T inferno_program ./wait-for-it.sh -t 0 reference_server:8080 -- bundle exec rake db:create db:migrate inferno:execute[http://reference_server:8080/reference-server/r4,onc_program,UsCoreR4CapabilityStatement,USCore311Patient,USCore311Allergyintolerance,USCore311Careplan,USCore311Careteam,USCore311Condition,USCore311ImplantableDevice,USCore311DiagnosticreportNote,USCore311DiagnosticreportLab,USC …
> made skips have return value 1 so task fails if there are skips

- lib/modules/core/shared_tests.rb
- lib/modules/onc_program/onc_ehr_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_restricted_launch_sequence.rb
- lib/modules/onc_program/smart_invalid_authorization_code_sequence.rb
- lib/modules/onc_program_module.yml
Some servers may revoke authorization code after negative test which blocks following tests in authorization test sequence. To avoid that, we moved negative authorization code tests to its own sequence as an additional test in "other" tab.
Replace two negative authorization code tests in ONC EHR Launch Sequece, ONC Standalone Launch Sequence, and ONC Standalone Restricted Launch Sequence 
Add Invalid Authorization Code Sequence
> Move negative authorization code tests to its own sequence

- lib/app/views/onc_program.erb
- lib/modules/onc_program/onc_standalone_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_smart_discovery_sequence.rb
- lib/modules/onc_program/onc_standalone_token_refresh_sequence.rb
- lib/modules/onc_program/shared_onc_launch_tests.rb
Inferno's sequences often overwrite certain shared state variables, which can be problematic if you want to have a later sequence use output from a specific instance of sequence prior (instead of just the last one that was run).  To work around this, in certain cases we save some of these variables under a separate name in a derived sequence, in the case where we do NOT want them overwritten.  For example, we save the bearer/refresh token that comes out of the 'Standalone Patient App' into a separate variables, because we want to revoke those specific tokens at the very end of the procedure (Other > Token Revocation) and don't want the other launches to overwrite those values.  
This fixes an issue that prevented the refresh token from being saved in a separate variable in a certain case, …
> FI-1287 Save bearer and refresh tokens to separate state variable in 1st launch

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/us_core_location_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_organization_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_patient_sequence.rb
- test/unit/sequence_base_test.rb
This addresses an issue where tests that searched against a string target value incorrectly failed. This happens because the validation checked if the searched value was the value in the resource. It should instead just check if the value in the resource starts with the searched value. https://www.hl7.org/fhir/search.html#string
Eg.) searching for family="test" might return two patients with family="test" and family="testing". The "testing" value would've incorrectly failed validation. 
Searches against string values will check that the value starts with the searched value.
I changed the validation portion of validate_resource_item for parameters that had a string search value.
> Fi 1262 search string starts with

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/bodyheight_sequence.rb
- lib/modules/uscore_v3.1.1/bodytemp_sequence.rb
- lib/modules/uscore_v3.1.1/bodyweight_sequence.rb
- lib/modules/uscore_v3.1.1/bp_sequence.rb
- lib/modules/uscore_v3.1.1/head_occipital_frontal_circumference_percentile_sequence.rb
- lib/modules/uscore_v3.1.1/heartrate_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_bmi_for_age_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_weight_for_height_sequence.rb
- lib/modules/uscore_v3.1.1/resprate_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_allergyintolerance_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_careplan_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_condition_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_note_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_documentreference_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_goal_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_immunization_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_implantable_device_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_medicationrequest_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_observation_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_procedure_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_pulse_oximetry_sequence.rb
Fix the failure on DiagnosticReport if patient does not exist
Code generator add line to skip search with patient id (except first search) if patient does not exist
uscore_generator.rb
add next if logic at get_search_params()
remove grab_first_value parameter from get_search_params() since it is not used by any caller
Add an no existing patient id to the input popup. All tests shall still pass
> FI-1215 Skip search with patient id if patient does not exist

- lib/app/views/layout.erb
- lib/app/views/missing_valuesets.erb
- lib/app/views/onc_program.erb
- lib/app/views/resource_validator_version.erb
- lib/app/views/state_status.erb
- lib/app/views/test_case.erb
- lib/version.rb
- public/css/styles.css
- public/js/app.js
IE11 is not technically end-of-life yet and may be used for embedded apps within EHRs until it is.  You have always been able to work around this using a modern browser to start the launch test, launching within the embedded IE11 browser, then switching back to the modern browser & refreshing (see #235).  This update fixes javascript/styling to allow IE11 to use Inferno, which makes it clear that the certification criteria does not specifically disallow IE 11.
IE11 no longer has an alert message stating it is not supported.  IE10 and before should still have this alert message.  IE11 should look exactly the same as chrome/firefox/safari.
I also slightly cleaned up the alert message when you do not have terminology installed, or are pointing to the wrong version of the validator service.
I …
> FI-1156 Fix issues in IE11 and slightly clean up certain alert message styling.

- db/config.postgres.yml
- db/config.yml
- db/migrate/20210804135524_add_request_index.rb
- db/schema.rb
- lib/app/utils/database.rb
This branch adds the missing index to join table to fix performance issues as the table size increases.
Also allows erb to be used in the database configuration so that values can be loaded from environment variables.
This should work:
```
docker-compose -f docker-compose.postgres.yml build
docker-compose -f docker-compose.postgres.yml up
```
You can validate that the environment variables work by adding something like this to the inferno service in `docker-compose.postgres.yml`, which will cause inferno to fail to connect to the database.
```
environment:
INFERNO_DB_USERNAME: xyz
```
> FI-1292/1293 Add missing index and allow dynamic content in db config

- config.yml
- lib/modules/core/shared_tests.rb
- lib/modules/onc_program/bulk_data_authorization_sequence.rb
- lib/modules/onc_program/onc_ehr_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_restricted_launch_sequence.rb
- lib/modules/onc_program/test/bulk_authorization_sequence_test.rb
Fix issue raised in #331 
* Deprecate BDA-03 from Inferno Program
* Update test_is_deprecated message from ' ... deprecated _from_ version ... ' to  ' ... deprecated _after_ version ...' because developer may not know the upcoming release number during development
* Remove unit tests for BDA-03
Multi-Patient test does not include BDA-03 "Authorization request fails when client supplies invalid scope" test
Open Multi-Patient tab
Verify BDA-03 is not listed
> FI-1296 Deprecate BDA-03 

- lib/app/utils/hl7_validator.rb
- test/unit/hl7_validator_test.rb
FHIR validator does not valid Resource.id 
So Inferno has to check Resource.id against this regex /^[A-Za-z0-9\-\.]{1,64}$/.
This PR addresses Issue #332 
Inferno will report "FHIR id value shall match Regex /^[A-Za-z0-9\-\.]{1,64}$/" error if the Resource.id does not match the regex
> FI-1294 Add Resource.id validation to hl7_validator

- lib/app/models/request_response.rb
- test/unit/request_response_test.rb
Fixes #326 where receiving an invalid header can crash Inferno. If you get rid of the `rescue` in `RequestResponse.stringify_headers`, an exception will cause the unit test to fail.
> FI-1302: Catch error from invalid headers

- lib/modules/onc_program/bulk_data_authorization_sequence.rb
- lib/modules/onc_program/test/bulk_authorization_sequence_test.rb
This PR addresses GitHub Issue: #348 
BDA-06 should accept server response with status code 401
change BDA-06 to use `assert_response_bad_or_unauthorized`
Test in unit test
> FI-1313: Add 401 as expected status to BDA-06

- lib/modules/onc_program/bulk_data_export_sequence.rb
- lib/modules/onc_program/test/bulk_patient_export_sequence_test.rb
This PR addresses Github Issue #279 
BDE-04 and BDE-05 are client requirements and should not be tested using server's responses
Deprecate BDE-04 and BDE-05
Verify that Multi Patient Group Compartment Export Tests does not include BDE-04 and BDE-05
> FI-1308: deprecate BED-04/05

- config.yml
This PR addresses GitHub Issue #344 
The JWKS  at [base]/inferno/.well-known/jwks.json contains both key_ops and use in public key.
Example:
```
"use": "sig",
"key_ops": [
"verify"
], 
```
Updated public keys in config.yml
Verify [base]/inferno/.well-known/jwks.json contains `"use": "sig",`
Verify Bulk Data Authorization sequence runs without error
> FI-1315 Add "usg: sig" to bulk data's public key

- lib/app/sequence_base.rb
- test/unit/sequence_base_test.rb
USCMR-14 failed because the resources from the 2nd page of search result don't have fhir client reference.
The root cause is on the SequenceBase.fetch_all_bundled_resources() function which does not use parse_reply for the response from "next" link.
Use bundle.next_bundle to get next page of search result.
bundle.next_bundle return nil if there is no next page or unable to read next page.
Remove one unit test on status 404 since bundle.next_bundle does not throw exception on status 404. Instead it returns nil.
Run Single Patient test on Reference Server to verify that USCMR-14 is passed.
> FI-1316 Call bundle.next_bundle to get next page of search result

- lib/modules/onc_program/bulk_data_authorization_sequence.rb
- lib/modules/onc_program/test/bulk_authorization_sequence_test.rb
This is a fix for #373 
Deprecate test BDA-02
BDA-02 is deprecated and not shown in Inferno Program Multi-Patient sequence
> FI-1348 Deprecated BDA-02

- db/migrate/20211020161758_add_column_bulk_timeout.rb
- db/schema.rb
- lib/app/models/testing_instance.rb
- lib/app/views/onc_program.erb
- lib/modules/onc_program/bulk_data_export_sequence.rb
- lib/modules/onc_program/bulk_data_group_export_sequence.rb
- lib/modules/onc_program/bulk_data_patient_export_sequence.rb
- lib/modules/onc_program/test/bulk_patient_export_sequence_test.rb
This PR address GitHub issue #359 
We added a UI input field for Bulk Data export status check timeout value
Tester can specify maximum timeout value for Bulk Data export status check.
If tester input value less than 1 or NAN, Inferno uses default 180 seconds.
When starting a Multi-Patient API test, the "Export times out after" shows at the bottom of popup dialog with default value 180.
> FI-1327 Add UI input field for bulk_timeout

- generator/uscore/metadata_extractor.rb
- lib/modules/uscore_v3.1.1/bodyheight_sequence.rb
- lib/modules/uscore_v3.1.1/bodytemp_sequence.rb
- lib/modules/uscore_v3.1.1/bodyweight_sequence.rb
- lib/modules/uscore_v3.1.1/bp_sequence.rb
- lib/modules/uscore_v3.1.1/heartrate_sequence.rb
- lib/modules/uscore_v3.1.1/profile_definitions/bodyheight_definitions.rb
- lib/modules/uscore_v3.1.1/profile_definitions/bodytemp_definitions.rb
- lib/modules/uscore_v3.1.1/profile_definitions/bodyweight_definitions.rb
- lib/modules/uscore_v3.1.1/profile_definitions/bp_definitions.rb
- lib/modules/uscore_v3.1.1/profile_definitions/heartrate_definitions.rb
- lib/modules/uscore_v3.1.1/profile_definitions/resprate_definitions.rb
- lib/modules/uscore_v3.1.1/profile_definitions/us_core_observation_lab_definitions.rb
- lib/modules/uscore_v3.1.1/profile_definitions/us_core_pulse_oximetry_definitions.rb
- lib/modules/uscore_v3.1.1/resprate_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_observation_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_pulse_oximetry_sequence.rb
This PR fixes GitHub issue #385, #364
Inferno decides to remove MustSupport check for Observation.dataAbsentResent and relies on invariant vs-2 to validate that "If there is no component or hasMember element then either a value[x] or a data absent reason must be present."
Add Observation.component MS check for observation-bp profile
Remove Observation.dataAbsentReason MS check from vital sign profile
add logic to remove dataAbsentReason to metadata_extractor
Check if tests still pass
> FI-1304 Adding Observation.component MS check for BP profile. Remove dataAbsentReason MS check from all vital sign profiles

- lib/modules/onc_program/onc_ehr_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_public_launch_sequence.rb
- lib/modules/onc_program/onc_standalone_restricted_launch_sequence.rb
- lib/modules/onc_program/shared_onc_launch_tests.rb
- lib/modules/onc_program/test/onc_ehr_launch_sequence_test.rb
- lib/modules/onc_program/test/onc_standalone_launch_sequence_test.rb
This PR addresses two GitHub Issues: #372 and #353 
1) SMART App Launch IG specifically mentioned `Person` as a possible resource type for `fhirUser` claim. So this PR added `Person` to the whitelist of predefined request scopes. Though Inferno test client does not list patient/Person.read by default, tester can add this scope as needed
2) RFC-6749 section 3.3 allows server to grant additional scopes beyond client's request. This PR relaxes the scope validations for received scopes
Verify that tester can manually add patient/Person.read to the Standalone Patient Scope at "Standalone Patient App" test
Server returns additional scope is tested by new unit tests.
> FI-1351 Allow server grants additional scopes

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/us_core_careteam_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_medicationrequest_sequence.rb
This PR fixes GitHub issue #312, #284
We updated composite-or search to
1) Generate search using all possible values for binding value set. All three composite-or searches have required binding for search element.
2) Collect expected values from previous seen resource.
3) Validate that the all expected values are seen in the composite-or search results 
Updates composite-or search in uscore_generator 
GitHub issue #312 has a sample MedicationRequest bundle.
> FI-1350 update composite_or test

- README.md
- lib/app/views/restricted_codesystems.erb
Fixes typo in the info box when codesystems are restricted for validation, and adds section in README on how to configure this.
Please review language.
> Add info on how to restrict access to codesystem validation.

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/us_core_careteam_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_medicationrequest_sequence.rb
The updated logic in the composite or searches do not properly filter out OperationOutcomes prior to checking return values.  This results in improper errors if the system returns an OperationOutcome.
If a system returns an OperationOutcome, alone with the resource types being searched for, it will no longer improperly fail.
Added a simple filter based on logic that is now bypassed in this section of the composite or test.
Unfortunately, we do not have a unit test for composite or searches.  There is no straightforward way to test this right now with our setup, unless you can mock up a server endpoint that injects an operation outcome.  We may consider adding a unit test section for composite-ors prior to merging this.
> FI-1367 Ensure operation outcomes are allowed in composite or search result.

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/bodyheight_sequence.rb
- lib/modules/uscore_v3.1.1/bodytemp_sequence.rb
- lib/modules/uscore_v3.1.1/bodyweight_sequence.rb
- lib/modules/uscore_v3.1.1/bp_sequence.rb
- lib/modules/uscore_v3.1.1/head_occipital_frontal_circumference_percentile_sequence.rb
- lib/modules/uscore_v3.1.1/heartrate_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_bmi_for_age_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_weight_for_height_sequence.rb
- lib/modules/uscore_v3.1.1/resprate_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_careplan_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_careteam_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_note_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_medicationrequest_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_observation_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_pulse_oximetry_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_smokingstatus_sequence.rb
It looks like at some point the generator code for testing reference searches with types was extracted into a variable, but that code wasn't removed from its original location, so these searches were being tested twice.
This change should not cause any behavior changes, other than the search not being performed twice.
> FI-1364: Fix duplicated search

- lib/modules/onc_program/bulk_data_export_sequence.rb
- lib/modules/onc_program/test/bulk_patient_export_sequence_test.rb
This is a fix of #390 
FHIR canonical URL allows version number to be attached at the end of url. BED-02 validates that CapabilityStatement has an operation defined by canonical url "http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export"
Using Regular Expression /^http://hl7.org/fhir/uv/bulkdata/OperationDefinition/group-export(\|\S*)?/ to validate canonical url
A new unit test is added to verify that BED-02 passed url with version
> FI-1366 BED-02 validate canonical url with version 

- lib/app/utils/hl7_validator.rb
- test/fixtures/hl7_validator_operation_outcome.json
- test/unit/hl7_validator_test.rb
This is a fix of GitHub issue #411 
HL7 validator v5.2.10 has a bug which causing validator error when the target profile is a reference, and that reference returns an empty list of target profiles
This is fixed in HL7 validator [v5.3.8](https://github.com/hapifhir/org.hl7.fhir.core/releases/tag/5.3.8)
Inferno program uses FHIR validator wrapper v1.2.0 which is based on HL7 validator v5.2.10.
Inferno suppresses validator errors ending with "... is not a valid Target for this element (must be one of [])" 
Inferno suppresses validator errors ending with "... is not a valid Target for this element (must be one of [])" 
Add exclude pattern to HL7Validator
Add unit test for HL7Validator
> FI-1379 Filter validator errors ending with "(must be one of [])"

- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/us_core_careteam_sequence.rb
- resources/uscore_v3.1.1/StructureDefinition-us-core-careteam.json
This is a fix for GitHub Issue #270 
StructureDefinition of US Core v3.1.1 CareTeam profile has `participant.member` element defined as `Reference(US Core Patient Profile | US Core Practitioner Profile | US Core Organization Profile)`.
HL7 validator rejects any US Core CareTeam resources with `participant.member` referencing to other FHIR core resources based on the US Core CareTeam StructureDefinition.
US Core v3.1.1 General Guidance [2.1.1.5](http://hl7.org/fhir/us/core/STU3.1.1/general-guidance.html#referencing-us-core-profiles) also states that 
```quote
Other resources allowed in the base FHIR specification may be referenced 
even though the current publication framework does not display them.
```
Inferno should not reject US Core CareTeam resources with `participant.member` …
> FI-1349 Add FHIR core resource types to US Core CareTeam profile participant.member  

- config.yml
- generator/uscore/uscore_generator.rb
- lib/modules/uscore_v3.1.1/bodyheight_sequence.rb
- lib/modules/uscore_v3.1.1/bodytemp_sequence.rb
- lib/modules/uscore_v3.1.1/bodyweight_sequence.rb
- lib/modules/uscore_v3.1.1/bp_sequence.rb
- lib/modules/uscore_v3.1.1/head_occipital_frontal_circumference_percentile_sequence.rb
- lib/modules/uscore_v3.1.1/heartrate_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_bmi_for_age_sequence.rb
- lib/modules/uscore_v3.1.1/pediatric_weight_for_height_sequence.rb
- lib/modules/uscore_v3.1.1/resprate_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_allergyintolerance_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_careplan_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_condition_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_diagnosticreport_note_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_documentreference_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_encounter_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_implantable_device_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_observation_lab_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_practitionerrole_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_procedure_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_pulse_oximetry_sequence.rb
- lib/modules/uscore_v3.1.1/us_core_smokingstatus_sequence.rb
This PR fixes GitHub Issue #412 
Inferno allows case-insensitive comparison on token value
Fix code generator for CodeableConcept data types in search_parameter_match_found method
> FI-1406 Allow case-insensitive comparison for token search

- config.yml
- docker-compose.postgres.yml
- docker-compose.yml
- lib/app/utils/hl7_validator.rb
- test/unit/hl7_validator_test.rb
This PR fix Github issue #414 
Update validator service dependency from v1.2.1 to v2.1.0
Removed validate_resource_id since this is handled by FHIR validator now.
> FI-1380 Update validator service to v2.1.0

- lib/app/views/deprecation_message.erb
- lib/app/views/index_onc_program.erb
Adds the following deprecation message:
> FI-1487 Add deprecation message.

- lib/tasks/tasks.rake
There was some code in `home.rb` that was necessary for bulk data tests to work, so if you ran them through the CLI the tests wouldn't work.
We should merge this, push a new image to inferno-program#latest, and update our reference server to test off `latest` instead of `release-latest`
> Fix CLI invoked tests for bulk data.

- lib/app/views/layout.erb
Closes #437 
None.
Adding meta tag, single file, small change.
I cannot verify on a mac.  IE is EOL very soon anyway (2-3 months from now).  I took the meta tag from the issue, [cross-referenced to microsoft docs](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/jj676915(v=vs.85)?redirectedfrom=MSDN) and read online.
> Add IE meta tag
